services:
  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-storage:/var/lib/grafana'
volumes:
  grafana-storage: {}

